org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

minecraft_version=1.21.1
neo_version=21.1.249

mod_id=createtradelogisticsoverhaul
mod_name=Create Trade Logistics Overhaul
mod_version=0.0.1
mod_group_id=com.vrlulu.createtradelogisticsoverhaul
mod_license=All Rights Reserved
mod_authors=VRLulu
mod_description=On-demand dispatching for Create logistics, plus a 3D logistics map in your browser.
