pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven { name = 'NeoForged'; url = 'https://maven.neoforged.net/releases' }
    }
}

plugins {
    // Lets Gradle download the Java 21 toolchain by itself
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.8.0'
}

rootProject.name = 'createtradelogisticsoverhaul'
